version: '2'

services:
    mysql:
        image: mysql:5.7
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: psreference
    reference-release:
        image: prestashop/prestashop:1.6
        volumes:
            - ./autoupgrade:/var/www/html/modules/autoupgrade
        environment:
            DB_SERVER: mysql
            DB_PASSWD: root
            DB_NAME: psreference
            PS_DOMAIN: localhost:8001
            PS_INSTALL_AUTO: 1
            PS_ERASE_DB: 1
            PS_FOLDER_ADMIN: hahahaha1234
            PS_FOLDER_INSTALL: install-dev
            PS_DEV_MODE: 1
            PS_LANGUAGE: fr
        depends_on:
            - mysql
        ports:
            - "8001:80"
